package com.shumaven.Admin.pojo;

public class blog_info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.githubsite
     *
     * @mbg.generated
     */
    private String githubsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.qqgroup
     *
     * @mbg.generated
     */
    private String qqgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.updatedate
     *
     * @mbg.generated
     */
    private String updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.id
     *
     * @return the value of blog_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.id
     *
     * @param id the value for blog_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.website
     *
     * @return the value of blog_info.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.website
     *
     * @param website the value for blog_info.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.githubsite
     *
     * @return the value of blog_info.githubsite
     *
     * @mbg.generated
     */
    public String getGithubsite() {
        return githubsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.githubsite
     *
     * @param githubsite the value for blog_info.githubsite
     *
     * @mbg.generated
     */
    public void setGithubsite(String githubsite) {
        this.githubsite = githubsite == null ? null : githubsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.qqgroup
     *
     * @return the value of blog_info.qqgroup
     *
     * @mbg.generated
     */
    public String getQqgroup() {
        return qqgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.qqgroup
     *
     * @param qqgroup the value for blog_info.qqgroup
     *
     * @mbg.generated
     */
    public void setQqgroup(String qqgroup) {
        this.qqgroup = qqgroup == null ? null : qqgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.version
     *
     * @return the value of blog_info.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.version
     *
     * @param version the value for blog_info.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.updatedate
     *
     * @return the value of blog_info.updatedate
     *
     * @mbg.generated
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.updatedate
     *
     * @param updatedate the value for blog_info.updatedate
     *
     * @mbg.generated
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate == null ? null : updatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.content
     *
     * @return the value of blog_info.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.content
     *
     * @param content the value for blog_info.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}