package com.shumaven.Admin.pojo;

public class blog_article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.edittime
     *
     * @mbg.generated
     */
    private Integer edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.view
     *
     * @mbg.generated
     */
    private Integer view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.mp3
     *
     * @mbg.generated
     */
    private String mp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.istop
     *
     * @mbg.generated
     */
    private Integer istop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.viewtumb
     *
     * @mbg.generated
     */
    private Integer viewtumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.articlepassword
     *
     * @mbg.generated
     */
    private String articlepassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.video
     *
     * @mbg.generated
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.file
     *
     * @mbg.generated
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.id
     *
     * @return the value of blog_article.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.id
     *
     * @param id the value for blog_article.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.title
     *
     * @return the value of blog_article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.title
     *
     * @param title the value for blog_article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.pic
     *
     * @return the value of blog_article.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.pic
     *
     * @param pic the value for blog_article.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.uid
     *
     * @return the value of blog_article.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.uid
     *
     * @param uid the value for blog_article.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.fid
     *
     * @return the value of blog_article.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.fid
     *
     * @param fid the value for blog_article.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ctime
     *
     * @return the value of blog_article.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ctime
     *
     * @param ctime the value for blog_article.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.edittime
     *
     * @return the value of blog_article.edittime
     *
     * @mbg.generated
     */
    public Integer getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.edittime
     *
     * @param edittime the value for blog_article.edittime
     *
     * @mbg.generated
     */
    public void setEdittime(Integer edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.view
     *
     * @return the value of blog_article.view
     *
     * @mbg.generated
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.view
     *
     * @param view the value for blog_article.view
     *
     * @mbg.generated
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.status
     *
     * @return the value of blog_article.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.status
     *
     * @param status the value for blog_article.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.mp3
     *
     * @return the value of blog_article.mp3
     *
     * @mbg.generated
     */
    public String getMp3() {
        return mp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.mp3
     *
     * @param mp3 the value for blog_article.mp3
     *
     * @mbg.generated
     */
    public void setMp3(String mp3) {
        this.mp3 = mp3 == null ? null : mp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.istop
     *
     * @return the value of blog_article.istop
     *
     * @mbg.generated
     */
    public Integer getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.istop
     *
     * @param istop the value for blog_article.istop
     *
     * @mbg.generated
     */
    public void setIstop(Integer istop) {
        this.istop = istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.viewtumb
     *
     * @return the value of blog_article.viewtumb
     *
     * @mbg.generated
     */
    public Integer getViewtumb() {
        return viewtumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.viewtumb
     *
     * @param viewtumb the value for blog_article.viewtumb
     *
     * @mbg.generated
     */
    public void setViewtumb(Integer viewtumb) {
        this.viewtumb = viewtumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.articlepassword
     *
     * @return the value of blog_article.articlepassword
     *
     * @mbg.generated
     */
    public String getArticlepassword() {
        return articlepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.articlepassword
     *
     * @param articlepassword the value for blog_article.articlepassword
     *
     * @mbg.generated
     */
    public void setArticlepassword(String articlepassword) {
        this.articlepassword = articlepassword == null ? null : articlepassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.video
     *
     * @return the value of blog_article.video
     *
     * @mbg.generated
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.video
     *
     * @param video the value for blog_article.video
     *
     * @mbg.generated
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.file
     *
     * @return the value of blog_article.file
     *
     * @mbg.generated
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.file
     *
     * @param file the value for blog_article.file
     *
     * @mbg.generated
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.type
     *
     * @return the value of blog_article.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.type
     *
     * @param type the value for blog_article.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.content
     *
     * @return the value of blog_article.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.content
     *
     * @param content the value for blog_article.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}