package com.shumaven.Admin.pojo;

public class blog_userdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.isVacate
     *
     * @mbg.generated
     */
    private Integer isvacate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.applyReason
     *
     * @mbg.generated
     */
    private String applyreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.applyTime
     *
     * @mbg.generated
     */
    private String applytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.isAgree
     *
     * @mbg.generated
     */
    private Integer isagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_userdetail.signTime
     *
     * @mbg.generated
     */
    private String signtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.Id
     *
     * @return the value of blog_userdetail.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.Id
     *
     * @param id the value for blog_userdetail.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.user_id
     *
     * @return the value of blog_userdetail.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.user_id
     *
     * @param userId the value for blog_userdetail.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.isVacate
     *
     * @return the value of blog_userdetail.isVacate
     *
     * @mbg.generated
     */
    public Integer getIsvacate() {
        return isvacate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.isVacate
     *
     * @param isvacate the value for blog_userdetail.isVacate
     *
     * @mbg.generated
     */
    public void setIsvacate(Integer isvacate) {
        this.isvacate = isvacate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.applyReason
     *
     * @return the value of blog_userdetail.applyReason
     *
     * @mbg.generated
     */
    public String getApplyreason() {
        return applyreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.applyReason
     *
     * @param applyreason the value for blog_userdetail.applyReason
     *
     * @mbg.generated
     */
    public void setApplyreason(String applyreason) {
        this.applyreason = applyreason == null ? null : applyreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.applyTime
     *
     * @return the value of blog_userdetail.applyTime
     *
     * @mbg.generated
     */
    public String getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.applyTime
     *
     * @param applytime the value for blog_userdetail.applyTime
     *
     * @mbg.generated
     */
    public void setApplytime(String applytime) {
        this.applytime = applytime == null ? null : applytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.isAgree
     *
     * @return the value of blog_userdetail.isAgree
     *
     * @mbg.generated
     */
    public Integer getIsagree() {
        return isagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.isAgree
     *
     * @param isagree the value for blog_userdetail.isAgree
     *
     * @mbg.generated
     */
    public void setIsagree(Integer isagree) {
        this.isagree = isagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_userdetail.signTime
     *
     * @return the value of blog_userdetail.signTime
     *
     * @mbg.generated
     */
    public String getSigntime() {
        return signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_userdetail.signTime
     *
     * @param signtime the value for blog_userdetail.signTime
     *
     * @mbg.generated
     */
    public void setSigntime(String signtime) {
        this.signtime = signtime == null ? null : signtime.trim();
    }
}