package com.shumaven.Admin.mapper;

import java.util.List;
import com.shumaven.Admin.pojo.blog_userdetail;
import com.shumaven.Admin.pojo.blog_userdetailExample;

public interface blog_userdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    int insert(blog_userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    int insertSelective(blog_userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    List<blog_userdetail> selectByExample(blog_userdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    blog_userdetail selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(blog_userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_userdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(blog_userdetail record);
}